title: Vignesh Perumal
subtitle: PhD, Mechanical Engineering & Mechanics
description: >- # this means to ignore newlines until "baseurl:"
  devlopr-jekyll is a beautiful Jekyll Theme Built For Developers, which is optimized for speed and readability.

url: "" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

# Navigation
urls:
    - text: About
      url: /about
    #- text: About
    #  url: /about
    #- text: Blog
    #  url: /blog
    - text: Portfolio
      url: /gallery
    #- text: Shop
    #  url : /shop
    - text: Contact
      url : /contact


# Edit Author details (For multi authors check _data/authors.yml)

author_logo: profile.png
author: Vignesh Perumal
author_bio: Hi, my name is Vignesh Perumal and I am a Ph.D. candidate with a research focus on developing fast design optimization algorithms for additive manufacturing. I acheive the improvement in speed by employing model order reduction in the form of artificial intelligence (AI) approaches such as Deep Learning. 
author_email: "vignesh.i.perumal@gmail.com"
author_location: USA
author_website_url: "https://DrVigneshPerumal.github.io"
typewrite-text: Advancing Additive Manufacturing with Computational Mechanics, Design Optimization, & Machine Learning
hero_cover_img: sample_cover.webp # replace this for changing homepage cover (eg. try cover.jpeg). Image should be in /assets/img

# Experiences
author_work_experiences:
            - company_name: Drexel University (worked with TAMG & MCMB- two of the leading groups at Drexel focused on AM and Design)
              company_logo: drexelU.png
              company_url: https://tamg.mem.drexel.edu/
              company_url: https://research.coe.drexel.edu/mem/mcmb/
              designation: Doctoral Research Fellow
              description: Combine data-driven modeling, design optimization, and computational mechanics to improve performance of metal AM parts.
              visibility: true
            - company_name: FEA Solutions
              company_logo: FEA Logo.jpg
              company_url: http://www.fea.co.in/
              designation: CAE Analyst
              description: Accelerate design to prototype in the aerospace, biomedical and heavy machinery insudtries using Computer-aided Engineering (CAE).
              visibility: true
            - company_name: Transinov Engitec
              company_logo: transinov-engitec-logo.jpg
              #company_url: https://microsoft.com
              designation: Design Engineer
              description: Developed turnkey solutions for engineering applications.
              visibility: true

# Education
author_education_details:
              - college_logo: drexelU.png
                college_name: Drexel University
                college_url: https://www.drexel.edu
                college_degree: PhD, MS
                description: Mechanical Engineering & Mechanics
                visibility: true
              - college_logo: UMumbai.webp
                college_name: University of Mumbai
                college_url: https://mu.ac.in/
                college_degree: B. Engg.
                description: Mechanical Engineering
                visibility: true

# Projects
author_project_details:
              - project_thumbnail: blank.png
  #              project_title: Gamers Hub
                project_description: [7] E. Tekerek, V. Perumal, L. Jacquemetton, D. Beckett, H.S. Halliday, B. Wisner, A. Kontsos*, “On the Process of Designing Material Qualification Type Specimens Manufactured using Laser Powder Bed Fusion” Materials & Design (2023) 

[6] V. Perumal, D. Abueidda, S. Koric, A. Kontsos*, “Temporal convolutional networks for data-driven thermal modeling of directed energy deposition”, Journal of Manufacturing Processes, (2023) 

[5] R. Yavari, A. Riensche, E. Tekerek, L. Jacquemetton, H. Halliday, M. Vandever, A. Tenequer, V. Perumal, A. Kontsos, Z. Smoqi, K. Cole, P. Rao*, “Digitally twinned additive manufacturing- Detecting flaws in laser powder bed fusion by combining thermal simulations with in-situ meltpool sensor data”, Materials & Design (2021) 

[4] V. Perumal, A. Najafi*, A. Kontsos*, “A Novel Digital Design Approach for Metal Additive Manufacturing to Address Local Thermal Effects”, Designs (2020) 

[3] P. Wadekar, V. Perumal, G. Dion, A. Kontsos, D. Breen*, “An optimized yarn-level geometric model for Finite Element Analysis of weft-knitted fabrics”, Computer Aided Geometric Design, (2020)  

[2] B. Wisner, P. Potstada, V. Perumal, K. Baxevanakis, M. G. R. Sause and A. Kontsos*, “Progressive Failure Monitoring and Analysis in Aluminum by In Situ Nondestructive Evaluation”, Fatigue & Fracture of Engineering Materials & Structures, (2019)  

[1] B.J. Wisner, K. Mazur, V. Perumal, K. Baxevanakis, L. An, G. Feng and A. Kontsos*, “Acoustic Emission Signal Processing Framework to Identify Fracture in Aluminum Alloys”, Engineering Fracture Mechanics, (2018) 
    #            project_url: https://gamershub.in
                visibility: true
      #        - project_thumbnail: hack4r.PNG
       #         project_title: Hack4r
        #        project_description: A Platform built for Hackers and Penetration Testers
         #       project_url: https://hack4r.com
          #      visibility: true




# social links
twitter_username: _vigneshperumal
github_username:  DrVigneshPerumal
#facebook_username: johndoe
linkedin_username: vigneshperumal
#behance_username: johndoe
#instagram_username: johndoe
#medium_username: johndoe
#telegram_username: johndoe
#dribbble_username: johndoe
#flickr_username: johndoe

#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )

# disqus_shortname: sujay-kundu
hyvor_talk_website_id: 476

# wakatime username (coding activity)
#wakatime_username: sujaykundu777

# mailchimp embedded form url (newsletter):
#mailchimp_form_url: https://sujaykundu.us10.list-manage.com/subscribe/post?u=50bab1c85eae24ecfb0f68361&amp;id=3a2dd721d0

# contact form - (choose formspress or getform)
# getform_endpoint: 83b703c3-9e47-4df4-ac55-e24d7eb02abc
formspree_email: vignesh.i.perumal@gmail.com

# releases - widget can be (sidebar, modal or embed)
#olvy_organization: devlopr
#olvy_widget_type: sidebar

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true

# pagination of posts
paginate: 4
per_page: 4
#paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

collections:
  products:
    output: true
  authors:
    output: true

defaults:
  -
    scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext
  -
    scope:
      path: ""
      type: authors
    values:
      layout: author
      permalink: /blog/authors/:slug
  -
    scope:
      path: 'assets/**'
    values:
      sitemap: false

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-admin

# Jekyll Admin Config
jekyll_admin:
  # hidden_links:
  #   - posts
  #   - pages
  #   - staticfiles
  #   - datafiles
  #   - configuration
  homepage: "about"


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.

### Switching Deployment Strategy (in DEPLOY_STRATEGY) file change the key accordingly:
# none - For no default
# gh-pages - For Github Pages
# firebase - For Firebase Hosting

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - assets/bower_components/isotope-layout/README.md
  - assets/bower_components/icono/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-svg-core/README.md
  - assets/bower_components/ghosthunter/README.md
  - assets/bower_components/nanobar/README.md
  - assets/bower_components/lightgallery/demo/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/free-brands-svg-icons/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/free-solid-svg-icons/README.md
  - assets/bower_components/jquery-mousewheel/README.md
  - assets/bower_components/get-size/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome/README.md
  - assets/bower_components/jquery-mousewheel/ChangeLog/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-regular/README.md
  - assets/bower_components/desandro-matches-selector/README.md
  - assets/bower_components/ev-emitter/README.md
  - assets/bower_components/font-awesome/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-solid/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-webfonts/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-brands/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-common-types/README.md
  - assets/bower_components/ghosthunter/example/Index.html
  - assets/bower_components/lightgallery/test/lightgallery.html
  - assets/bower_components/masonry-layout/README.md
  - assets/bower_components/imagesloaded/README.md


destination: ./build
